apiVersion: v1
kind: Template
metadata:
  name: suggestion-application-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: suggestion
    labels:
      app: suggestion
      group: fis.example.eventmatch
      version: ${APP_VERSION}
  spec:
    replicas: 1
    selector:
      app: suggestion
      group: fis.example.eventmatch
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: suggestion
          group: fis.example.eventmatch
          version: ${APP_VERSION}
      spec:
        containers:
        - image: ''
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: suggestion:${APP_VERSION}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: suggestion
      expose: "true"
      group: fis.example.eventmatch
      version: ${APP_VERSION}
    name: suggestion
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: suggestion
      group: fis.example.eventmatch
      provider: fabric8
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: suggestion
    labels:
      app: suggestion
      group: fis.example.eventmatch
      version: ${APP_VERSION}
  spec:
    port:
      targetPort: http
    to:
      kind: Service
      name: suggestion
      weight: 100
parameters:
  - name: APP_VERSION
    value: latest