apiVersion: v1
kind: Template
metadata:
  name: calendar-build-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: calendar
    labels:
      app: calendar
      group: fis.example.eventmatch
      version: ${APP_VERSION}
  spec:
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-fuse70-java-openshift:1.0
          namespace: openshift
    output:
      to:
        kind: ImageStreamTag
        name: calendar:${APP_VERSION}
    source:
      binary: {}
      type: Binary
    runPolicy: Serial
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    nodeSelector: {}
    postCommit: {}
    resources: {}
    triggers: []
parameters:
  - name: APP_VERSION
    value: latest