camel:
  springboot:
    name: Event
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /*

management:
  port: 8081

endpoints:
  enabled: false
  health:
    enabled: true